project:
  type: website
  resources:
    - media/mu_wave.mp4
    - media/distributions.png
    - media/house_price.png
    - media/rent.png
    - media/acceptances.jpeg
    - media/applications.jpeg
    - media/occupancy.PNG
    - media/Bluesky_Logo.svg

website:
  title: "Deon Roos"
  description: "Lecturer in Applied Statistics | Data Visualisation | Statistics Course | Statistical Distributions"
  navbar:
    left:
      - text: "My Courses"
        file: courses.qmd
      - text: "Stats Explainers"
        file: explainers.qmd
      - text: "My Output"
        file: publications.qmd
      - text: "My CV"
        file: cv.qmd
      - text: "Blog"
        file: blog/index.qmd

format:
  html:
    theme: default
    css: styles.css
    highlight-style: atom-one-dark

publish:
  provider: gh-pages
  branch: gh-pages
