project:
  type: website
  resources:
    - media/mu_wave.mp4
    - media/distributions.png
    - media/house_price.png
    - media/rent.png

website:
  title: "Deon Roos"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Courses"
        file: courses.qmd
      - text: "Works"
        file: publications.qmd
      - text: "Curriculum Vitae"
        file: cv.qmd

format:
  html:
    theme: default
    css: styles.css

publish:
  provider: gh-pages
  branch: gh-pages
