project:
  type: website
  resources:
    - media/mu_wave.mp4
    - media/distributions.png
    - media/house_price.png
    - media/rent.png
    - googleac99a2840748e25e.html

website:
  title: "Deon Roos"
  description: "Lecturer in Applied Statistics | Data Visualisation | Statistics Course | Statistical Distributions"
  navbar:
    left:
      - text: "Courses"
        file: courses.qmd
      - text: "Works"
        file: publications.qmd
      - text: "CV"
        file: cv.qmd

format:
  html:
    theme: default
    css: styles.css

publish:
  provider: gh-pages
  branch: gh-pages
